# permissions for end users to edit redisbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisbackup-editor-role
rules:
- apiGroups:
  - app.devspace.com
  resources:
  - redisbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.devspace.com
  resources:
  - redisbackups/status
  verbs:
  - get
